### ISSUE TITLE
Relative module names

### ISSUE THREAD

**Issue by yrns** [stealjs/live-reload#12]
In the example for the reload function with module name ("app/router"), the name is relative. But for me it appears the name needs to be fully normalized as a URL which is somewhat unwieldly. Is this because I'm using SystemJS and not Steal?

**Comment by matthewp** [comment]
The name `app/router` is fully normalized. It's true that SystemJS uses urls instead of names now (Steal still uses names) so it's a less nice to use with SystemJS, but this is a general problem with SystemJS as they've chosen a user-unfriendly key representation.  However I believe there is a utility for converting names to URLs?  `System.normalizeSync` maybe?

**Comment by matthewp** [comment]
Going to close for now, let me know if you have more questions.
